import type { Metadata } from "next";
import "./globals.css";
import MenuPage from "@/components/WebComponents/MenuPage";
import FooterPage from "@/components/WebComponents/FooterPage";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import AlertCookies from "@/components/WebComponents/AlertCookies";
import { NotificationProvider } from "@/providers/NotificationProvider";

export const metadata: Metadata = {
  title: "Meredith Aesthetic",
  description: "Generated by Abasotech Company",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        <ReactQueryProvider>
          <NotificationProvider>
            <MenuPage />
            {children}
            <FooterPage />
          </NotificationProvider>
        </ReactQueryProvider>
        <AlertCookies />
      </body>
    </html>
  );
}
